version: '3.1'
services:
  mysql:
    image: mysql:8.0
    container_name: ${DOCKER_PROJECT_NAME:-application}-mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    working_dir: /application
    volumes:
      - .:/application
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE:-application}
      MYSQL_USER: ${DOCKER_MYSQL_USER:-application}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD:-123}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD:-123}
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
  nginx:
    image: nginx:alpine
    container_name: ${DOCKER_PROJECT_NAME:-application}-nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${DOCKER_NGINX_PORT:-80}:80"
  php-fpm:
    build: etc/docker/php-fpm
    container_name: ${DOCKER_PROJECT_NAME:-application}-php-fpm
    working_dir: /application
    user: root
    environment:
      DATABASE_URL: mysql://${DOCKER_MYSQL_USER:-application}:${DOCKER_MYSQL_PASSWORD:-123}@mysql/${DOCKER_MYSQL_DATABASE:-application}?serverVersion=5.7
    volumes:
      - .:/application
      - ./etc/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
