projects_index:
  path: /projects
  controller: App\Project\Controller\ProjectController::index
  methods:
    - GET

projects_create:
  path: /projects/create
  controller: App\Project\Controller\ProjectController::create
  methods:
    - GET
    - POST

projects_edit:
  path: /projects/{slug}/edit
  controller: App\Project\Controller\ProjectController::edit
  methods:
    - GET
    - POST

project_overview:
  path: /projects/{slug}/overview
  controller: App\Project\Controller\ProjectController::overview
  methods:
    - GET

project_issues:
  path: /projects/{slug}/issues
  controller: App\Project\Controller\ProjectController::issues
  methods:
    - GET