<?php

declare(strict_types=1);

namespace App\Task\Collection;

use App\Task\Model\Task;
use Doctrine\Common\Collections\ArrayCollection;
use Webmozart\Assert\Assert;

/**
 * @extends ArrayCollection<int, Task>
 */
class TaskCollection extends ArrayCollection
{
    /**
     * @param array<int, Task> $elements
     */
    public function __construct(array $elements = [])
    {
        Assert::allIsInstanceOf($elements, Task::class);

        parent::__construct($elements);
    }

    public function add($element): bool
    {
        return parent::add($element); // TODO: Change the autogenerated stub
    }
}