parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # App\Project

    App\Project\Controller\ProjectController:
        parent: App\Shared\Controller\AbstractController

    App\Project\Slug\ProjectSlugGenerator:
        decorates: App\Shared\Slug\SlugGeneratorInterface
        arguments:
            - '@App\Project\Slug\ProjectSlugGenerator.inner'


    # App\Shared

    App\Shared\Controller\AbstractController:
        tags: ['controller.service_arguments']

    App\Shared\Slug\IntlTransliteratorSlugGenerator: ~

    App\Shared\Slug\SlugGeneratorInterface: '@App\Shared\Slug\IntlTransliteratorSlugGenerator'

